import math  # for max function on positive numbers only due to lower bounding rule in Python range() is exclusive end point (lower boundary). So we import the module here.  
            
def choose_num(x, y):    
    """This function takes two Positive Numbers x and Y as input parameters 
       It returns The largest even integer number that falls within [X:Y] inclusive inclusively if any such exist otherwise return -1"""        
           # For example select num is a positive int larger than or equal to X but smaller Than equals (and including) the value of Y.   If it exists, then we got our result; else just returns default negative one (-1).  It should be noted that for non-integer values x and/or y Python will round down if they are not integers so either would work fine in this case
    """      # Documentation string with function's purpose.   Example: In some scenarios, like choose_num(30,-2), it can return max even number between 15 & inf which is '14'. It should be noted that for non-integer values x and/or y Python will round down if they are not integers so either would work fine in this case
     # Example usage:   print choose_num(30,-2) => prints "Choosing 6" because the largest even number between [15,Inf] inclusive is '4'. """   
        for num in range (x+1 ,y-1):       # Start from x and go down to y -1. Python's Math module does not include end point by default so we do a trick using 2 step decrement which makes it loop till the next largest integer smaller than given number excluding
            if num % 2 == 0:         # Checking for even numbers only (since odd will be excluded due to range function's exclusive property)   Python uses modulus operator ("%") with '2', thus we can check whether a variable is divisible by two or not. If yes, it means the number being checked if an Even Number 
                return num            # and hence this condition returns that particular value which was set earlier in loop because there's no other even integer within [x:y] range found beforehand   (returning). In case of None matches so far none is returned by function.    If not, the next line executes only when a match has occurred and does nothing otherwise 
        return -1                 # This would happen if there's no even number in [x:y] range found beforehand or loop execution ends normally (no more numbers to check). Here 'return num;', because we want it returned for this case. Python uses "None" as a value that signifies absence of any object and thus, the last non-none statement executed is considered successful in if block ie., return None