def find_max(words):
    max_len = -1
    result = None
   # We iterate over all words in the list and update `result` with word having maximum unique characters. If we get a new highest length, it updates also our previous results that have same high character count (i.e., are lexicographically smaller). 
     for w in sorted(words):    #sorted is used to make sure all words first come together when the list has multiple strings with maximum unique characters because Python sorts alphabets/strings by ASCII values which will be same if we sort them manually. For example, 'name' comes before or after each other but their ASCIICodes are different thus sorted based on its length of word and then lexicographically
        count_unique = len(set([char for char in w]))  # set is used to remove all duplicate characters from a string so as we only need unique character.   If you use list because it counts the duplicates but not exactly what's expected, consider using tuple or other data structure which does no have dups
        if count_unique > max_len:    #if new word has more number of uniques characters and first comes before any previous maximum unique character words then assign that as our result.  Otherwise we keep the lexicographically smaller one among all found until now (result).   The comparison is done using len(set()) which will not consider order in a list but it can be used to compare strings because Python does its string comparing based on ASCII values and if both are equal then just considering their position.
            max_len = count_unique  # update the maximum length we have found so far for these words (if any)
            result = w    # set this word as our new 'best' one when a longer string is encountered because of more unique characters now, and since list(sorted()) keeps its sorted order among strings with same max_unique count.  When it comes to the case where there are multiple such words which have maximum length in lexicographical (dictionary) way then first come appears as expected due Python's internal sorting mechanism when we iterate over all elements of list, if one string has more unique characters than another strings and they both appear after sorted(words), this is considered to be the 'first appearance'.
    return result  # Return word which contains maximum number or duplicate lexicographically.   If no valid words then it returns None as expected in a programming scenario because function should always have an output, if there's not any such case we need something that can indicate absence of data ie., null/None (like 'null'/'').