def reverse_delete(s, c):  # defining function here.  
    for char in s :        # Iterating through all characters inside string 's'.          
         if char==c or not isinstance (char , str) and any (x == char[0] != x[-1][-2:]      )     .any():       # checking condition to remove the character from "S".  Here we are using list slicing. It checks whether 's' has same characters in reverse order as it is or not, if yes then delete that and repeat again for all other string till its end
            s = char + s[1:]   # Removing matching chars by removing from start of the remaining part  .any() : This will return True when any character matches with condition otherwise False. If a match found it returns true else false, we are using list slicing here to remove that matched characters and repeat again
    if s==s[::-1]:   # Check for palindrome in the remaining string  .any() : This will return True when 'string' is same as its reverse. If yes then it returns true otherwise false, we are using list slicing here to get reversed version of given strings and check if this matches with original or not
        result= s   # Assigns the remaining string into variable for returning  .any() : This will return True when 'string' is same as its reverse. If yes then it returns true otherwise false, we are using list slicing here to get reversed version of given strings and check if this matches with original or not
        Check=True   # Assigns the boolean value "true" into variable for returning  .any() : This will return True when 'string' is same as its reverse. If yes then it returns true otherwise false, we are using list slicing here to get reversed version of given strings and check if this matches with original or not
    else:   # For all other scenarios assigns the remaining string into variable for returning  .any() : This will return True when 'string' is same as its reverse. If yes then it returns true otherwise false, we are using list slicing here to get reversed version of given strings and check if this matches with original or not
        result= s   # Assigns the remaining string into variable for returning  .any() : This will return True when 'string' is same as its reverse. If yes then it returns true otherwise false, we are using list slicing here to get reversed version of given strings and check if this matches with original or not
        Check=False # Assigns the boolean value "false" into variable for returning  .any() : This will return True when 'string' is same as its reverse. If yes then it returns true otherwise false, we are using list slicing here to get reversed version of given strings and check if this matches with original or not
    # Return statement that contains the result string alongwith boolean value  .any() : This will return True when 'string' is same as its reverse. If yes then it returns true otherwise false, we are using list slicing here to get reversed version of given strings and check if this matches with original or not
    print (result , Check)   # Prints the result string alongwith boolean value  .any() : This will return True when 'string' is same as its reverse. If yes then it returns true otherwise false, we are using list slicing here to get reversed version of given strings and check if this matches with original or not