def remove_vowels(text):   ## Complete the function here. It should return a new string with vowel removed from given text and it shouldn't modify original data since there is no requirement to keep or store them in some other place then we use str datatype instead of list as result
    """ 
        This method takes input which might contain several sentences, each sentence will be treated separately. Then remove all vowels from the given text and return new string without any extra spaces between words (sentences) or at end/start lines if there are multiple word separated by '
'. If no character found in set 'aeiouAEIOU' then it returns empty String
    """   ## Add necessary docstring here.  For example, add the number of vowels removed etc to describe what this function does and also provide sample inputs/outputs for a clear understanding how different test cases are handled by your method (if any).     >>> remove_vowels('')    
    """''""" ## The docstring can be modified according to requirements. It must include the complete functionality of that python code block followed with its purpose and usage in examples 
        >>> 
   def myFunction(input):      
        pass                     ## Put your function implementation here, then use print statements or testing tools/methods for calling it as necessary (if any) to test different scenarios.     >>>myfunction('')    ## Test the case of empty string     'abc'  ,,, efg   '','',''', etc...
        pass                     ## Add more tests cases here if required according to function requirement and behavior         ...""","""""","###"]]]])")})")))     >>> remove_vowels('aaBAA')    ## Test case for a string containing both uppercase vowel(s).       '''AB'''
        pass                     ## Add more tests cases here if required according to function requirement and behavior         ...""","""""","###"]]]])")}))))))  ]]}}}}}    >>> remove_vowels('zbcd')    ## Test case for a string containing no vowel(s)          '''ZBCD'''
        pass                     ## Add more tests cases here if required according to function requirement and behavior         ...""","""""","###"]]]])")}))))  ]]}}}}}    >>> remove_vowels('abcdef
ghijklm')    ## Test case for a string with multiple sentences separated by '
'.      '''BCDF
        ghjKLM'''          """))         'abcdfg',,, '' ,, '', etc...   ...""","""""","###"]]]])")})"))  ]]}}}}}    >>> remove_vowels('aEiOuA')    ## Test case for a string containing upper and lower vowel(s).        '''BCD'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('aeiou')    ## Test case for a string containing only vowel(s).        ''''''
         pass                     ## Add more tests cases here if required according to function requirement and behavior      ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('bcdfg')    ## Test case for a string containing only vowel(s).        '''BCDFG'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('12345')    ## Test case for a string containing only vowel(s).        ''''''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('AEIOU')    ## Test case for a string containing uppercase vowel(s) with spaces.      '''BCD'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('bcdfgheijklmno')    ## Test case for a string containing multiple sentences with vowel(s) separated by '
'.      '''BCDFGHEJKLMNO'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('abcdefghijklmnopqrstuvwxyz')    ## Test case for a string containing multiple sentences with vowel(s) separated by '
'.      '''BCDFGHEJKLMNO'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('AEIOU')    ## Test case for a string containing uppercase vowel(s) with spaces.      '''BCD'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('AEIOU')    ## Test case for a string containing uppercase vowel(s) with spaces.      '''BCD'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('AEIOU')    ## Test case for a string containing uppercase vowel(s) with spaces.      '''BCD'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('abcdefghijklmnopqrstuvwxyz')    ## Test case for a string containing multiple sentences with vowel(s) separated by '
'.      '''BCDFGHEJKLMNO'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('AEIOU')    ## Test case for a string containing uppercase vowel(s) with spaces.      '''BCD'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('AEIOU')    ## Test case for a string containing uppercase vowel(s) with spaces.      '''BCD'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('AEIOU')    ## Test case for a string containing uppercase vowel(s) with spaces.      '''BCD'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('aeiou')    ## Test case for a string containing only vowel(s).        ''''''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('bcdfg')    ## Test case for a string containing only vowel(s).        '''BCDFG'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('12345')    ## Test case for a string containing only vowel(s).        ''''''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('AEIOU')    ## Test case for a string containing uppercase vowel(s) with spaces.      '''BCD'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('bcdfgheijklmno')    ## Test case for a string containing multiple sentences with vowel(s) separated by '
'.      '''BCDFGHEJKLMNO'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('AEIOU')    ## Test case for a string containing uppercase vowel(s) with spaces.      '''BCD'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('aeiou')    ## Test case for a string containing only vowel(s).        ''''''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('bcdfg')    ## Test case for a string containing only vowel(s).        '''BCDFG'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('12345')    ## Test case for a string containing only vowel(s).        ''''''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('AEIOU')    ## Test case for a string containing uppercase vowel(s) with spaces.      '''BCD'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('bcdfgheijklmno')    ## Test case for a string containing multiple sentences with vowel(s) separated by '
'.      '''BCDFGHEJKLMNO'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('AEIOU')    ## Test case for a string containing uppercase vowel(s) with spaces.      '''BCD'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('aeiou')    ## Test case for a string containing only vowel(s).        ''''''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('bcdfg')    ## Test case for a string containing only vowel(s).        '''BCDFG'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('12345')    ## Test case for a string containing only vowel(s).        ''''''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('AEIOU')    ## Test case for a string containing uppercase vowel(s) with spaces.      '''BCD'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('bcdfgheijklmno')    ## Test case for a string containing multiple sentences with vowel(s) separated by '
'.      '''BCDFGHEJKLMNO'''
         pass                     ## Add more tests cases here if required according to function requirement and behavior       ...""","""""","###"]]]])")})))  ]]}}}}}    >>> remove_vowels('AEIOU')    ## Test case for a string containing uppercase vowel(s) with spaces.      '''BCD'''
```   Python is full of such simple and clear tasks that can be done in just one or two lines, not to mention they have the ability even if you are beginner level programmers like yourself could do it at least a little bit easily because we know how python works from many other languages. It’s been made for handling almost all sort of data types and is very efficient too – easy-to read code can be debugged by anyone as well, not to mention that with Python you don't need declare the variable type so it knows what kind of value should hold in there at any given moment.