def right_angle_triangle(a, b, c):
    # Sort the input lengths to get longestSide as side 'c' (hypotenuse) and 2 shorter ones are always in pairs. So I will use them one by one until a^2 + nextSmallerSquare ^2 == maxLength^2 which is possible for all three numbers i, j & k where c = maxlength
    sorted_sides=[a**2+b**2 ,c ** 2]   # Initially longestSide and shorter side square are found out. But now we have to find whether the sum of lengths can form a right angle triangle or not using Pythagorean theorem by checking it with each other pair i, j & k where c = maxlength
    sorted_sides=[a**2+b**2 ,c ** 2]   # Initially longestSide and shorter side square are found out. But now we have to find whether the sum of lengths can form a right angle triangle or not using Pythagorean theorem by checking it with each other pair i, j & k where c = maxlength
    for x in range(1,(c//2)+1):  # Start iterating from side 'b' (shorter one), till square of half length is less than or equal to summed lengths. This condition will be satisfied when the longestSide^2 equals maximumLength^2 + nextSmallerSquare ^2
        if sorted_sides[0] == x**2: # If true then it means we have found our pair, Now checking for remaining side which is smaller than or equal to c/ 3 and greater with b (the shortest one) because now both sides are known. Then check whether the sum of lengths can form a right angle triangle by comparing these two pairs
            if sorted_sides[1] == ((c-x)**2): # If true then it means we have found our remaining pair, Now there is only 3 side left for finding hypotenuse. So return True as per the given problem statement otherwise False (either because sides do not form a right angle triangle or more than one set of pairs did all exist and hence they are false)
                if c==x: # To handle two equal numbers, ie both shorter side length will be 'c' then returning true since it forms an equilateral traingle. 
                    return True  
        else :    continue     # If not same or pair doesnot exist do nothing and move to next number in sorted_sides list which is (b^2 + c^2) - x ^ 2 . And keep repeating this process until the end of given pairs are done. This will handle all possible scenarios where one length can form a triangle