from collections import Counter  # Python's built-in module for counting objects or elements inside a list/array in python language
  
def histogram(s):   
     if not s:          # If the string is empty, return an empty dictionary. It means no data found so far...
         return {}       
      
     c = Counter(s.split())  # Using count function from collections module to get counts of all characters in list/string 'str'  
     
     max_count = 0          # Initializing maximum repetition frequency as zero for each character firstly...   
          
     res={}                 # Empty resultant dictionary will be initiated, 
                             # which we can fill up with the letter(s) having highest count.  
     
     for k in c:             # Iterating through characters of 'str' (i.e., keys from Counter), and...   
         if max_count<c[k]: # If current character frequency is higher than maximum recorded, then update it too.... 
           max_count=c[k]   # Update the count as well which has highest occurrence of any letter in 'str'.....    
     
       res = {s.split()[0]:max_count}    # If we found a new character(with higher frequency than current maximum) with same letters, then add it to resultant dictionary...  
         
          
        return (res if max_count == 1 else 'All characters have the highest repetition')  # Returning specific messages when all data is processed or some letter's count was more ...   
    		                 	# than others. Else, It means no character has repeated a higher number of times..  	   	 	       	                 # hence it returns an empty dictionary...