def is_prime(n):     # check for primality using a simple approach - divide by all numbers up to sqrt(N). If none are divisible, N must be prime.  
    if n == 1 : return False 
    elif n <= 3 : return True     
      
    elif (not (n %2) and not (n%3)):     # reduces the problem by eliminating multiples of numbers which can't form palindrome part(e.g., from checking for prime number or two different odd digits being opposite to each other.) 
        return False      
  
    i=5               
    while (i * i <= n):     # this loop runs till sqrt of N, and increases the counter by incrementing 'j' in every iteration. This is a common way for optimization when we are checking if number `n` has factor other than 1 & itself or prime no which gives us faster result
        j = 2         
  
    while (i * i <= n) :      # this loop runs till sqrt of N, and increases the counter by incrementing 'j' in every iteration. This is a common way for optimization when we are checking if number `n` has factor other than 1 & itself or prime no which gives us faster result
        while (i % j != 0) :      # check divisibility until i becomes non-divisible by the loop counter 'j'. Increment J. If not found, increment I and repeat this process till square of N is less than `n`  because a larger factor has already been checked in previous loops
            if (i % j == 0):      # This condition checks whether i can be divided into two different factors or more which would result the number being non-palindrome. If so, we increment 'j' by one and repeat this process till square of N is less than `n`  because a larger factor has already been checked in previous loops
                break       # Break loop when above conditions are not met as it leads to an even better optimization result (i++) with same prime factors. This saves unnecessary computations for the rest part 'j' > sqrt(N).   If i is completely divisible by J then N must be non-palindrome and we increment `J`
        j = i + 1              # Incrementing both I (number being checked) & J as well. This will ensure that all potential factors of 'n' have been considered in the worst case scenario to prevent false negatives with a larger N  by one factor beyond sqrt(N). Hence, we increase `i` and decrese counter j for every iteration
    return True               # Return whether i is divisible or not. This ensures that all potential factors of 'n' have been considered in the worst case scenario to prevent false negatives with a larger N by one factor beyond sqrt(N). Hence, we increment `i` and decrese counter j for every iteration
    
def even_odd_palindrome_(maximum):  # function definition including comments   
        """Given positive integer n. Return tuple that has the number of both kinds (even/both odd-and also palinrodme) numbers in range(1, maximum). Inclusive."""  
       if not isinstance(maximum,(int)):     raise TypeError("Input should be a Integer")    # check type  - Input must be integer. Otherwise return error message and inform user to input correct data format (Integer only allowed here).. this will stop the execution of function in case wrong inputs are given
        if maximum <= 0 or not isinstance(maximum,(int)):   raise ValueError("Input should greater than zero") # check value - Input must be a positive integer. Otherwise return error message and inform user to input correct data format (Positive integers only allowed here).. this will stop the execution of function in case wrong inputs are given
        even, odd = 0 , 0     # Initialise count for both types palindrome numbers as zero   - Initialize counter variable with zeros    //This way we can get total number from each kind.//       If not initialized then Python will throw an error and that's why it’s recommended to initialize them before any operation
        i = 1     # Start looping sequence till maximum (exclusive)   - Starting for a series of numbers until the `maximum` input value, we use variable 'i'. This is because in every iteration number will be checked if they are palindrome or not. Hence it’s needed to increment this counter on each iterate
        while i < maximum:     # Checking condition till our current loop (sequence) goes up until `maximum`   - We check all the numbers from 1 through 'i' and see whether them meet both conditions(both even/odd or palindrome). If yes, increment either of counter variable.
            if is_prime((2 * i + 1)):     # Checking for prime number condition      //Condition to ensure a non-palinromic sequence starts with the odd no and ends in an Even No.. this ensures that we only consider Palindrome numbers among those which start from Odd & end at even.
                if is_prime(i):           # Prime check  - Check for prime number using helper function defined above     //This will ensure all sequence starts with a single odd no and ends in an Even No.. so, this ensures that we only consider Palindrome numbers among those which start from Odd & end at even.
                    if i %2 == 0:          # checking condition for palinromic number  - This checks whether the current value is both Prime (both odd or neither) and also a Even no.. so it will ensure that we only consider Palindrome numbers among those which start from Odd & end at even.
                        if i >= maximum :     raise ValueError("Input should be less than equal to "+str(maximum)) # check for input value exceeding limit - This ensures the function doesn't go out of range and stops execution with proper error message..  this will stop program in case wrong inputs are given
                        even += 1        # Increment counter if it is palindrome number   //If condition meets, increment count variable indicating Palinromic Odd/Even numbers.    If not met then simply return the same value without any change of them (for next iteration) or raise an exception to stop execution with proper error message..  this will continue program in case conditions are correct
                    else :      # if i is odd no, increment count variable indicating Palinromic Odd/Even numbers. If not met then simply return the same value without any change of them (for next iteration) or raise an exception to stop execution with proper error message..  this will continue program in case conditions are correct
                else :      # if i is even no, increment count variable indicating Palinromic Odd/Even numbers. If not met then simply return the same value without any change of them (for next iteration) or raise an exception to stop execution with proper error message..  this will continue program in case conditions are correct
            else :      # if i is odd no, increment count variable indicating Palinromic Odd/Even numbers. If not met then simply return the same value without any change of them (for next iteration) or raise an exception to stop execution with proper error message..  this will continue program in case conditions are correct
            j = 2          # Incrementing both i and J as well   - This ensures that all potential factors for 'i' have been considered. Hence, we increment `J` by one each iteration of loop run till square root N is less than maximum . Also this helps to find only prime numbers from 1 through sqrt(N).
            while (j * j <= i) :      # This process runs until the current value 'i' and increases its counter variable. If not met, then simply return values or raise an exception.. stops execution with proper error message when conditions are correct .. continue program in case all factors have been considered correctly –
                if (j %2 == 0) :     # This checks whether `J` is even no   - Ensures that we only consider prime numbers among those starting from odd ending at an Even No. So, this ensures the loop does not go out of range and stops execution with proper error message.. 
                    if (i >= maximum):    raise ValueError("Input should be less than equal to "+str(maximum)) # check for input value exceeding limit - This ensure that program doesn't get beyond specified `n` or stop executing in case wrong inputs are given. So this will continue the loop with proper error message and stops execution..
                    else :      raise ValueError("Input should be less than equal to "+str(maximum)) # check for input value exceeding limit - This ensure that program doesn'   t get beyond specified `n` or stop executing in case wrong inputs are given. So this will continue the loop with proper error message and stops execution..
                j = i + 1     # Increment both 'i'(counter) & J(increasing counter by one each time). This ensures that all potential factors for every single number from 2 through sqrt of `n` have been considered. Hence, we increment this value in the loop till square root N is less than maximum . Also helps to find only prime numbers upto n as well..
            i += 1     # Incrementing both 'i'(counter) & J(increasing counter by one each time). This ensures that all potential factors from 2 through sqrt of `n` have been considered. Hence, we increment this value in the loop till square root N is less than maximum . Also helps to find only prime numbers upto n as well..
        return (even , odd)     # Returning tuple containing counts for both kinds(both/odd-and palindrome). If not met then simply returns values or raise an exception. In this way, we ensure that all different type of factors are considered in the best possible scenario and stops execution with proper error message..