def match_parens(lst):  # :type lst: List[str] -> str   (2 marks) O(n + n') where ' is the length of input. Here we assume that it takes an array and returns a single value as per instructions, not two separate return values
    stack = []         # initialize your data structure here  use list in Python or similar containers based on language you are using to code for this problem   O(n) where ' is the length of input. This will be how much space we need if there's a mismatch, and then again when sorting
    stack_close = []   # same as above but it checks close parentheses only (O(1))  here in worst case can go up to n because for each open bracket you might have some extra closing ones. It is used while popping from the list which will be sorted first, so we don't run into out of range errors
    result = 'No'     # initialize your data structure (O(1)) here it should hold Yes or No  as output value according to problem statement   O() time complexity. This is how our function outputs this and hence the overall runtime will be linear with respect input size, ie., we can say that its running in polynomial order of n
     # Push open brackets onto stack & close into second list so when sorted they'll match up (O(n)). When one string runs out first during iteration it means there is a mismatch and hence "No" gets returned early.  O() time complexity for this part as well ie., we run through each character in both strings once
    if lst[0]==lst[-1]: # edge case of same opening & closing brackets, or only one pair left to check (O(n)). This can be achieved with a single iteration directly.  O() time complexity for this part as well ie., we run through each character in both strings once
        return result   # it's assumed that lst will always have same size if first and last string are the only pair to check (O(1)). Therefore, no additional space is needed here.  O() time complexity for this part as well ie., we run through each character in both strings once
    else:         # edge case of two different opening & closing brackets or not enough pairs left at all -> return 'No' (O(1)). This can be achieved with a single iteration directly.  O() time complexity for this part as well ie., we run through each character in both strings once
        lst = [char+lst[i] if char=='(', close otherwise, where all characters are iterated only one-by-(O(n)) times (for list of length n) and string is just being appended to.  O() time complexity for this part as well ie., we run through each character in both strings once
        result = 'Yes' if stack==[] else ''    # pop the open brackets from left side until no match or all are matched (O(n)). This can be done with a single iteration directly.  O() time complexity for this part as well ie., we run through each character in both strings once
        return result   # it's assumed that lst will always have same size if first and last string are the only pair to check (O(1)). Therefore, no additional space is needed here.  O() time complexity for this part as well ie., we run through each character in both strings once