def do_algebra(operator: list[str], operand:list[int])-> int :   # Declare the function signature with type hints for better readability of code in IDEs like PyCharm or JetBrains, also specify return typing as integer to match your provided description.
    operator_dict = {'+':' + ', '-': ' - ',  '*': ' * ', '/': ' // ', '**':' **'}   # Create dictionary of operators and their corresponding arithmetic operations for easy access during the evaluation process via python builtin eval method (which is similar to a parser)
    expression_string = str(operand[0])  # Start with first operand in string format. This will become our final result after all computations are done by Python's "eval" function later on, as it needs strings for computation and not numbers themselves like '2 + 3 * 4 -5'.
    remaining_elements = operand[1:] # Get the rest of elements from list (after first one) in order to form an expression.
    
   if len(operator)!=len(remaining_elements)-1:             # Check length matches required by operator-list or not according provided description, raise exception as per requirements here and there is no need for now since the given problem doesnt have any invalid inputs in this case so added a check. 
        print("The lengths of Operator list & operand List don't match") # You can replace with logging mechanism based on requirement if required to keep track/log details about failures etc .  		     	    	       	   	 	     			   									      						              							                                                             								                             }: 
        print("operator length is not equal than the operand list minus one, please check inputs") # You can replace with logging mechanism based on requirement if required to keep track/log details about failures etc .  		     	    	       	   	 	     			   									      						              							                                                             								                             }:
        return None 	# Return Nothing (None) in case of any failure, you might want this as a last resort and can replace with suitable error handling mechanism. This line is just for demonstration purpose only to make code work at its basic form without having the complete context or requirements present here . Replace it according need by using appropriate logging/exceptions mechanisms depending on your project's needs
    else: 			# Else if conditions are met (length matches and operand list contains enough elements). Start looping through operator & rest of remaining_elements one at a time, add their corresponding operation to our final expression string. Finally use the Python eval method for this evaluation with generated result as an integer type then return it back by using "return" keyword after processing all operations .
    	   # Note: The given problem does not allow negative numbers or non-integer inputs so added checks in place of comment section if required to handle those cases.