from typing import List  # type hinting for the return value of function in Python is optional but recommended by PEP8 guide line, hence added here to make sure that your code can be understood. We're using this kind of annotation because it helps other developers understand what a certain part (function/method) expects and returns when invoked from outside world

def separate_paren_groups(paren_string: str) -> List[str]:  # type hinting for the parameter is optional but recommended by PEP8 guide line, hence added here to make sure that your code can be understood. We're using this kind of annotation because it helps other developers understand what a certain part (function/method), which we are going call as 'separate_paren_groups', expects and returns when invoked from outside world
    stack = []  # Declare an empty list to use in place for our braces, so far. This will simulate the usage of stacks that you may encounter with parentheses at a basic level (addition/removal are done on one end). A 'list' is also used because it allows Python lists as part of its type and can be treated like an array in other languages
    groups = []  # Declare the list which will hold all separate grouped strings. This helps keep track over time so that once we have collected all possible balanced parentheses, this final result is returned to us via function call for our usage purpose only as it's not required after calling back from Python
    new_group = ''  # Initialize a variable which will act like the stack in real life (addition/removal are done on one end). It starts off empty because we haven’t seen any braces yet. This is useful when you want to keep track of what's happening while iterating over your list or string
    for char in paren_string:  # Iterate through each character (i) inside the given parentheses group/input, and perform actions on them if needed like ignoring spaces etc. The loop variable is used as a helper to indicate where we are currently within our process of processing characters from input string
        new_group += char   # Adds current character into 'newGroup' (which simulates how stack works in real life). We do this because the purpose here isn’t merely add/remove items. It is actually adding them to a running list where we can then form separate groups once all braces have been closed
        if char == "(":  # When it encounters an opening brace, ie (addition happens on one end)...
            stack.append(new_group[:])   # Add the current group formed up to this point into our list of 'stack' where all groups are kept till now in form as a string for easy retrieval later using indexing if required and it simulates how stacks work (i e, addition/removal happens on one end)
            new_group = ''  # Reset the current group to start with an empty state so that we can add more into this up till next opening brace is found. This helps keep track of what's happening while iterating over your list or string and also keeps all groups in sync, because it’ll be keeping a close relationship here
        elif char == ")":  # When encounters closing parenthesis... (addition/removal happens on one end).. Here we pop the items from 'stack' till last opening brace is found if any. If no braces are left in stack, then there’s nothing more to add and it just simulates how stacks work
            groups.append(''.join(stack.pop()))   # Add current group formed upto this point into our list of 'groups' where all finalized or complete strings will be kept till now using indexing if required.. This helps keep track over time so that once we have collected the necessary balanced parentheses, these groups are stored in a form to return back via function call for usage purpose only.
    # The returned list of grouped string is then finally ready and can serve as an output from this method on its own or used elsewhere based upon needs (like logging/display) if needed at the end which simulates how you might use your stack in real life scenario to solve problems like finding out all balanced parentheses groups.
    return groups  # We are returning 'groups' list as result after completing our process of processing input string and forming separate grouped strings upto last brace has been found, so it is ready for usage purpose only or used elsewhere in your code using this method to solve a specific task based upon needs at the end