def encode_cyclic(s: str) ->str :   # Function definition with type hint in paramters. It also has doc string for better readability of the function and returns encoded result as String by cycling groups of three characters if length is 3 or less than that then leaves it same
    """returns encoded string cycly"""     #Docstring describes what this function does, here we are encoding a given text (s) with cycle operation. Cyclic means moving the first character to end ie group by one place in left and rest will be moved as is for circular arrangement of characters  
    groups = [ s[3*i:min(3*(i+1), len(s))]  for i in range((len(s) + 2 ) // 3)]     # Splitting the string into group each with length three and remaining less than size. These are stored inside a list "groups"
    groups = [group[1:] + group[:1] if len(group) == 3 else group for group in groups ]   # Cycle operation is performed on every 3 character long substring (i.e., each element of the `groups`). If length less than three it remains same and leave other cases as they are
    return ''.join(groups )     # Concatenating all elements inside a list to form complete encoded string, then returning that result in String format 
  
def decode_cyclic (s: str) ->str :      // Function definition with type hint. It also has docstring for better readability of the function and returns original text if length is not multiple groups are present or more than one character left as it remains same else return remaining characters after cycling operation
    """Decodes encoded string returned by encode_cyclic"""   //Docstring describes what this code does. Here we are decoding a given strings (s) that has been previously transformed through cycle operations, and returning original text if length of the input is not multiple groups or more than one character remains in less case otherwise return remaining characters after cycling operation
    """Decodes encoded string returned by encode_cyclic"""   //Docstring describes what this code does. Here we are decoding a given strings (s) that has been previously transformed through cycle operations, and returning original text if length of the input is not multiple groups or more than one character remains in less case otherwise return remaining characters after cycling operation
    """Decodes encoded string returned by encode