def largest_smallest_integers(lst):    # Define the Python function named 'largest_smallest' which accepts argument (a list) called lst. It returns a tuple of two elements where first one is maximum negative integer and second element is minimum positive Integer from given List if such integers exist otherwise it will return None for both
  try:   # Try block to catch any possible exception that might be raised during execution in case the passed argument 'lst' isn’t list or doesn”t have at least one number. Else, continue with else statement and code inside this bracket is executed only when no error occurs within "try"
    neg_integers = [i for i in lst if i<0]  # List comprehension to get all negative integers from given list 'lst' using a loop over each element of the lists. If it found any, else returns an empty array which is considered as None by Python when there’s nothing inside that
    non_negatives = max(filter(lambda i:i>=0 , neg_integers)) if len(neg_integers) != 0 else None  # use filter function to only include numbers >= 0 and find the maximum. If all elements are negative, then it returns none (Python’s equivalent of an empty list). Else return max value
    pos_numbers = [i for i in lst if i>1]   # List comprehension to get positive integers from given 'lst' using a loop over each element. If there are no numbers, it returns None (Python’s equivalent of an empty list). Else return min value
    smallest_nonnegative = min(filter(lambda x:x>=0 , pos_numbers)) if len(pos_numbers) != 0 else None  # use filter function to only include non-negatives and find the minimum. If all elements are negative, then it returns none (Python’s equivalent of an empty list). Else return min value
    largest = max(lst)   # Find maximum integer in given 'list' using builtin Python functions/methods like filter() or without looping over each element to find the biggest number. If there is no positive numbers, then it returns none (Python’s equivalent of an empty list). Else return Biggest Integer
    smallest = min(lst)   # Find minimum integer in given 'list' using builtin Python functions/methods like filter() or without looping over each element to find the smalleset number. If there is no negative numbers, then it returns none (Python’s equivalent of an empty list). Else return smallest Integer
    if neg_integers==None and pos_numbers == None:   # Check whether all elements are either positive or both non-negative integers exist in the given 'list' otherwise we will not be able to calculate anything.  If this condition holds true, then it returns none as there is no answer possible
      return (largest , smallest) if largest !=None and smallest!= None else () # Returns a tuple with two elements: first element maximum negative integer from list(if exist), second one minimum positive Integer in the given List. Else empty Tuple 
    elif neg_integers==[] or pos_numbers == []:   # If there is no Negative numbers inside lst, and/or if it contains only non-negative integers then returns None for both (as required by problem statement) else return maximum negative integer(if exist), minimum positive Integer in the given List
      largest = neg_integers  or pos_numbers   # If there is no Negative numbers inside lst, this will be set to False and if it contains only non-negative integers then last element of that list (i.e., smallest number) should have been returned as expected by problem statement
      return largest , smallest    # Returns a tuple with two elements: first one maximum negative integer from List(if exist), second - minimum positive Integer in the given lst if available otherwise it returns empty Tuple  or both are None (as required by above conditions)  	      	   	       			              		       
     else : return largest , smallest # In all other cases, this will be a normal tuple with two elements: first one maximum negative integer from List(if exist), second - minimum positive Integer in the given lst if available otherwise it returns empty Tuple.  This line of code is to handle scenarios when none or both non-negative integers are found within 'lst'
   except Exception as e : # Catch all exception, useful for debugging only and not essential part by itself but good practice anyways due its role in error handling & making the program more robust 	   	       	 		   	         									    	     			         (e is name of python variable that holds actual object)
        return None ,None # This will be executed if there was an exception and it returns two elements as 'None' otherwise they remains empty tuple like before. Anyway, this line can’t really exist without the previous lines being called by some sort or another part in code which is a best practice according to programmer standards