import math  # We'll use some mathematical function from Python Standard Library. For example: 'math.sqrt()'. It returns square root of a number and is often used in prime checking functions to find out upper limit for potential divisor candidates. This also helps avoid unnecessary computation - you don’t have your checks all the way up till sqrt(n), only until √ n that's why we use it here
    
def is_prime(num):   # Define function, parameter num (integer) expected to be checked if prime or not. Num should start from a non-negative integer because by convention all numbers less than the square root of number can have no factor otherthan 1 and itself that leaves you with positive value for checking primality
    """Return true when given input is Prime, false otherwise"""   # Docstring explaining what this function does. In Python comments are docstrings (docuementation in python). They start from 'def' keyword to define a method or any code block and then follows by ':'. It explains the expected inputs/outputs of your functions
         if num <= 1:    # If given number is less than 2, it cannot be prime. We return false for such cases as per mathematical definition (prime numbers start from int greater than one) so that'll help with input validation in our function call 'is_prime(x)' where x could either come integer or float
             False    # Return a boolean value of True/False based on given condition. In this case, number is less then 2 ie non-positive and hence not prime (return false) so return something else - any other than zero would imply it's Prime in the mathematical sense which Python takes as true
         elif num == 2:   # This handles only perfect square numbers right now. In future if you wanted to expand this functionality for larger sets, then just check these values instead of all odd or even integers until sqrt(n) like we do here because our current function will return false on 4 and above
             True     # Return a boolean value based upon inputted condition (if number is perfect square integer), if so true otherwise False. In this case, given num was either '2' ie the only even prime or already checked as such then it must be Prime thus we should return something else - anything but zero
         elif not is_square(num):  # Check for factors of number apart from square root (this will make sure to reduce unnecessary computations) if given num was a perfect Square integer, this would mean that the numbers are in pair or already been handled above so it's enough and we return true.
             all((n % divisor == 0)  # All function returns True only when each condition is fulfilled ie 'True'. Here checking for factors of number apart from square root upto sqrt(num). If any factor then false else finally if not found anything other than zero (i'm making sure no checks are made beyond this point as we know n must be prime)
             return True    # Return true once all conditions have been fulfilled. In each condition, it only returns False/None when the input is incorrect and 'True'/any value else depending on what was expected or returned from previous operations in function call ‘is_prime(x)' where x could come integer (negative / zero).
             for divisor in range((2), int(math.sqrt(num)) + 1):   # Checking all possible factors upto sqrt of given number, so as long we're checking till the square root because beyond that point factor would have already been covered by check above (already checked perfect squares).
                 if num % divisor == 0:  # If there exists any numbers which can evenly divide into 'num'. Then it means n is not prime hence return False. Else, as soon returns true when first such number found that makes function call returning True ie the given value of inputted by user would be identified and marked to satisfy conditions so we should exit immediately from our loop
                     return False   # Return a boolean result for condition in which case you have returned false (i.e., your 'num' was not prime), else when found one divisor among all factors ('divisors') then it must also be True and hence, function call will stop executing this block of code immediately returning value as mentioned above
             return False   # Return a boolean result for the condition in which case you have returned false (i.e., your 'num' is prime), else when no factors found among all within our loop then it should be True and hence, function call will stop executing this block of code immediately returning value as mentioned above
     def sqrt(n):   # A separate square root finder from math module for speed ups. This method finds the exact divisor only (not including pair or multiple) in case a perfect number is given - it just gives us one possible solution to check primality, which would be more efficient than checking all numbers until sqrt(n).
          return n ** 0.5   # Return square root of 'num' as float result due because math module only returns integer part if input was an int or a decimal number like in this case (square roots are always integers) but we need it to be able to stop looping after first factor found, so let the caller decide whether our final return value should also include square root of 'n'
```    # Ends Python Function for is_prime method. Please feel free asking if you want more explanation or understanding about this code!   I appreciate your support and help in improving my skills with codingPython programmer as well