def special_factorial(n):  # Function Definition (continued)
    """The Brazilian factorial is defined as..."""    
        
        if n == 0 : return None   # Handle the base case of zero input, returning none. This should be considered for other cases where '1' might not exist or would underflow program flow due to a non-positive integer being passed in function argument  Here we consider that special_factorial(n) = 1 (which is defined as n!), because factorial has no effect when inputting zero.
        
        # Calculate Factors, looping from '2' till given number and multiplying each step to get final result   . This results in calculating the multiplication of all numbers upto `n` ie., (1*...* n) , which is actually equivalent as computing factorial here.  For example:
        # special_factorial(4), it would be '((special_factorial)(3)) * ((special_factorial)(2))' . Which equals to "6*"8"=576, ie., the value of `n!` multiplied by (each factor from 1 upwards till n).
        result = 1   # Initialize 'result', which is our output. We start with one as we are multiplying all values in loop below it - this means that if input was a valid integer greater than zero, the function will return its Brazilian Factorial equivalent value (n!), else returns None or any appropriate exception when n < 0 
        for i in range(1 , n + 1):    # Loop from 'start' to end of numbers. It means we are going through all multiples till `number` which is given as input, and multiply each one with result (which already has initial value set at "one").   For example: if the number passed in was 4 , it would loop over every integer from '1' to ('special_factorial(4)', ie., up till n), incrementing by ones on each iteration.
            # Loop inside a for-loop, here we are going through all multiples of `i` (ie.'from 2,'to','n') and multiplying them with 'result' in loop which is already set to one initially as per requirement - so it will keep getting updated by each product.
            result *= i   # Loop inside a for-loop, here we are going through all multiples of `i` (ie.'from 2,'to','n') and multiplying them with 'result' in loop which is already set to one initially as per requirement - so it will keep getting updated by each product.
        return result   # Return the final computed value, this would be our output for given input n! . If a non-positive integer was passed (which does not make sense), then function should handle that scenario and either returns None or appropriate exception depending upon requirements set in docstring of Function definition ie., 'returning none when zero is entered.